model:
  name: "svnet"
  version: "1.0.0"
  description: "A project for implementing the svnet model."
  
data:
  train_data_path: "data/train.csv"
  test_data_path: "data/test.csv"
  
training:
  epochs: 50
  batch_size: 32
  learning_rate: 0.001
  
logging:
  level: "INFO"
  log_file: "logs/training.log"